### ISSUE TITLE
Package 'crul' also needed, 'nneo' not available for R3.5.1

### ISSUE THREAD

**Issue by mjones01** [cyverse-gis/NEON-Shiny-Browser#1]
Hi.  Two issues both related to packages installs (My set up OS: Mac 10.13.6,  R Version: 3.5.1). 

1) Following the installation instructions in the README, I also needed to install 'crul' to get the app to run.  You may want to add that into the instructions. 

2) I received an error that the package 'nneo' was needed but 'nneo' is not available for R 3.5.1.  As far as I know, 'nneo' is not being maintained as many of the features are available with 'neonUtilities'.  It was removed from CRAN in November 2018.  An archive version is available. 
-- due to this second issue, I'm unable to run the app.

**Comment by Danielslee51** [comment]
Hey Megan,

Thanks for telling me about these issues. Today was my first time opening up the application in a while, so I ran into the exact same problems. I'll dig into them, and get back to you when I fix the issue!

**Comment by Danielslee51** [comment]
All fixed!

**Comment by mjones01** [comment]
@Danielslee51 I went to update and run the code to try out your app but I see no recent changes to this repo.  Am I missing something?  Thanks.

**Comment by Danielslee51** [comment]
Ah, I forgot to commit. My bad!

Daniel Lee
University of Arizona
